---
title: "Function testing"
author: "Lauren Buckley"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Function testing}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
##Load TrenchR package
library(TrenchR)
```

#UtilityFunctions

```{r}
day_of_year("2017-01-01", format= "%Y-%m-%d")
day_of_year("2014-12-31", format= "%Y-%m-%d")
day_of_year("2007-04-22", format= "%Y-%m-%d")

#CHECKED
```

```{r}
plot(1:365, dec_angle(1:365), type="l")
#CHECKED against https://www.pveducation.org/pvcdrom/properties-of-sunlight/declination-angle
```

```{r}
plot(1:365, daylength(lat=47.61, doy=1:365), type="l", ylim=c(0,24))
points(1:365, daylength(lat=10, doy=1:365), type="l", lty="dashed")
points(1:365, daylength(lat=60, doy=1:365), type="l")

#CHECKED
```

```{r}
plot(1:365, solar_noon(lon=-122, doy=1:365), type="l", ylim=c(10.8, 13))
points(1:365, solar_noon(lon=-180.335, doy=1:365), type="l")
points(1:365, solar_noon(lon=-150, doy=1:365), type="l", lty="dashed")
#points(1:365, solar_noon(lon=-60, doy=1:365), type="l")

#CHECKED
```

```{r}
#across hours
zen= unlist(lapply(1:24, FUN=zenith_angle, doy=200, lat=47.61, lon=-122.33))
plot(1:24, zen, type="l")
zen= unlist(lapply(1:24, FUN=zenith_angle, doy=0, lat=47.61, lon=-122.33))
points(1:24, zen, type="l", lty="dotted")
zen= unlist(lapply(1:24, FUN=zenith_angle, doy=100, lat=47.61, lon=-122.33))
points(1:24, zen, type="l")
zen= unlist(lapply(1:24, FUN=zenith_angle, doy=300, lat=47.61, lon=-122.33))
points(1:24, zen, type="l", lty="dashed")

zen= unlist(lapply(1:24, FUN=zenith_angle, doy=200, lat=10, lon=-122.33))
plot(1:24, zen, type="l")
zen= unlist(lapply(1:24, FUN=zenith_angle, doy=0, lat=10, lon=-122.33))
points(1:24, zen, type="l", lty="dotted")
zen= unlist(lapply(1:24, FUN=zenith_angle, doy=100, lat=10, lon=-122.33))
points(1:24, zen, type="l")
zen= unlist(lapply(1:24, FUN=zenith_angle, doy=300, lat=10, lon=-122.33))
points(1:24, zen, type="l", lty="dashed")

zen= unlist(lapply(1:24, FUN=zenith_angle, doy=200, lat=70, lon=-122.33))
plot(1:24, zen, type="l")
zen= unlist(lapply(1:24, FUN=zenith_angle, doy=0, lat=70, lon=-122.33))
points(1:24, zen, type="l", lty="dotted")
zen= unlist(lapply(1:24, FUN=zenith_angle, doy=100, lat=70, lon=-122.33))
points(1:24, zen, type="l")
zen= unlist(lapply(1:24, FUN=zenith_angle, doy=300, lat=70, lon=-122.33))
points(1:24, zen, type="l", lty="dashed")

#solar angle at noon across doy
zen= unlist(lapply(1:365, FUN=zenith_angle, hour=12, lat=60, lon=-122.33))
plot(1:365, zen, type="l", ylim=range(0,90))
zen= unlist(lapply(1:365, FUN=zenith_angle, hour=12, lat=40, lon=-122.33))
points(1:365, zen, type="l", lty="dotted")
zen= unlist(lapply(1:365, FUN=zenith_angle, hour=12, lat=20, lon=-122.33))
points(1:365, zen, type="l")
zen= unlist(lapply(1:365, FUN=zenith_angle, hour=12, lat=0, lon=-122.33))
points(1:365, zen, type="l", lty="dashed")

#CHECKED
```

```{r}
az= unlist(lapply(1:24, FUN=azimuth_angle, doy=33, lat=52.51, lon=13.41))
plot(1:24, az, type="l")
az= unlist(lapply(1:24, FUN=azimuth_angle, doy=112, lat=47.61, lon=-122.33))
plot(1:24, az, type="l")
az= unlist(lapply(1:365, FUN=azimuth_angle, hour=10, lat=47.61, lon=-122.33))
plot(1:365, az, type="l")
#CHECKED
```

```{r}
plot(1:4000, airpressure_from_elev(1:4000), type="l")
#CHECKED: https://www.engineeringtoolbox.com/air-altitude-pressure-d_462.html
```

```{r}
fahrenheit_to_kelvin(85)
kelvin_to_celsius(270)
fahrenheit_to_celsius(85)
#CHECKED
```

```{r}
radian_to_degree(0.831)
degree_to_radian(47.608)
#CHECKED
```


#TempWindProfileFunctions

```{r}
surface_roughness(u_r=c(0.01,0.025,0.05,0.1,0.2), zr=c(0.05,0.25,0.5,0.75,1))

#CHECKED
```
```{r}
zs= seq(0,2,0.1) 
us= wind_speed_profile_neutral(u_r=1, zr=2, z0=0.2, z=zs)
plot(us,zs, type="l")
points(wind_speed_profile_neutral(u_r=0.5, zr=2, z0=0.2, z=zs), zs, type="l", col="red")
points(c(0.5,1),c(2,2) )

#CHECKED
```

```{r}
z.seq <- seq(0, 2, by = 0.1)
t.seq <- air_temp_profile_neutral(T_r=20, zr=1, z0=0.2, z=z.seq, T_s=25)
plot(t.seq, z.seq, type = "l", xlab = "Temperature (C)", ylab = "z (height above ground in m)")
points(c(25,20),c(0,1) )

#CHECKED
```

```{r}
zs= seq(0,2,0.1) 
us= wind_speed_profile(u_r=1, zr=2, z0=0.2, z=zs)
plot(us,zs, type="l")
points(c(1),c(2))
points(wind_speed_profile(u_r=0.5, zr=2, z0=0.2, z=zs), zs, type="l", col="red")
points(c(0.5),c(2), col="red")

#CHECKED
```

```{r}
z.seq <- seq(0, 2, by = 0.1)
t.seq <- air_temp_profile(T_r = 20, u_r = 0.5, zr = 2, z0 = 0.2, z = z.seq, T_s = 25)
plot(t.seq, z.seq, type = "l", xlab = "Temperature (C)", ylab = "z (height above ground in m)")
points(c(25,20),c(0,2) )

#CHECKED
#CHANGED FROM NICHE MAPPER VIGNETTE
```
```{r}
z.seq <- seq(0, 2, by = 0.1)
t.seq= lapply(z.seq, FUN=air_temp_profile_segment, T_r=c(25,22,20),u_r=c(0.01,0.025,0.05), zr=c(0.05,0.25,0.5), z0=c(0.01,0.15,0.2), T_s=27)
plot(t.seq, z.seq, type = "l", xlab = "Temperature (C)", ylab = "z (height above ground in m)")
points(c(27,25,22,20),c(0,0.05,0.25,0.5) )

#CHECKED
```

```{r}
z.seq <- seq(0, 2, by = 0.1)
u.seq= lapply(z.seq, FUN=wind_speed_profile_segment, u_r=c(0.01,0.025,0.05), zr=c(0.05,0.25,0.5), z0=c(0.01,0.15,0.2))
plot(u.seq, z.seq, type = "l", xlab = "Wind speed (m/s)", ylab = "z (height above ground in m)")
points(c(0.01,0.025,0.05),c(0.05,0.25,0.5) )

#CHECKED
```

#DTR Functions
```{r}
t.seq= lapply(1:23, FUN=diurnal_temp_variation_sineexp, T_max=30, T_min=10, t_r=6, t_s=18)
plot(1:23, t.seq, type = "l", xlab = "hour", ylab = "temp (C)")
#CHECKED
```

```{r}
plot(1:23, diurnal_temp_variation_sine(T_max=30, T_min=10, t=1:23), type = "l", xlab = "hour", ylab = "temp (C)")
#CHECKED
```

```{r}
plot(1:23, diurnal_temp_variation_sinesqrt(t=1:23, tr=6, ts=18, T_max=30, T_min=10, T_minp=12), type = "l", xlab = "hour", ylab = "temp (C)")
#CHECKED
```

#Degree days
```{r}
degree_days(T_min=7, T_max=14, LDT=12, UDT=33, method="single.sine")
degree_days(T_min=7, T_max=14, LDT=12, UDT=33, method="double.sine")
degree_days(T_min=7, T_max=14, LDT=12, UDT=33, method="single.triangulation")
degree_days(T_min=7, T_max=14, LDT=12, UDT=33, method="double.triangulation")

#CHECKED
```

#Radiation functions
```{r}
zen= unlist(lapply(1:24, FUN=zenith_angle, doy=200, lat=47.61, lon=-122.33))
zen= zen*2*pi/360
rd= lapply(zen, FUN=estimate_radiation, doy=200, tau=0.6, elev=1500, rho=0.7)
#unlist
rd=matrix(unlist(rd), nrow=3, byrow=FALSE)
plot(1:24, rd[1,], type="l", xlab = "hour", ylab = "radiation (W/m^2)", ylim=c(0,1600))
points(1:24, rd[2,], type="l")
points(1:24, rd[3,], type="l")
points(1:24, rd[1,]+rd[2,]+rd[3,], type="l", lty="dashed")

#Campbell & Norman Figure 11.2 and 11.3
psi.seq <- seq(0, 90, by = 5)
rd= lapply(psi.seq*2*pi/360, FUN=estimate_radiation, doy=200, tau=0.75, elev=1500, rho=0.7)
#unlist
rd=matrix(unlist(rd), nrow=3, byrow=FALSE)
plot(psi.seq, rd[1,], type="l", xlab = "zenith angle (degrees)", ylab = "radiation (W/m^2)", ylim=c(0,1200))
points(psi.seq, rd[2,], type="l")
points(psi.seq, rd[3,], type="l")
points(psi.seq, rd[1,]+rd[2,], type="l", lty="dashed")

#CHECKED
```

```{r}
r.seq= lapply(1:24, FUN=diurnal_radiation_variation, doy=172, solrad=8000, lon=-112.07, lat=33.45)
plot(1:24, r.seq, type = "l", xlab = "hour", ylab = "radiation (W/m2)")

#CHECKED
```

```{r}
r.seq= lapply(seq(1,365,31), FUN=monthly_solar_radiation, lat=43.57,lon=-116.22,elev=866,T=20,Hr=15,P=15)
r.seq=unlist(r.seq)
plot(seq(1,365,31), r.seq, type = "l", xlab = "doy", ylab = "radiation (W/m2)")

#CHECKED against Nikolov and Zeller (1992) Fig. 3 for Boise, Idaho. Not radiation unit differences.
```

#Radiation partitioning functions

```{r}
r.seq= lapply(seq(0,1,0.1), FUN=partition_solar_radiation, method="Erbs", lat=40, sol.elev=60)
plot(seq(0,1,0.1), r.seq, type = "l", xlab = "kt", ylab = "radiation (W/m2)", ylim=c(0,1))
r.seq= lapply(seq(0,1,0.1), FUN=partition_solar_radiation, method="Liu_Jordan", lat=40, sol.elev=60)
points(seq(0,1,0.1), r.seq, type = "l")
r.seq= lapply(seq(0,1,0.1), FUN=partition_solar_radiation, method="Orgill_Hollands", lat=40, sol.elev=60)
points(seq(0,1,0.1), r.seq, type = "l")
r.seq= lapply(seq(0,1,0.1), FUN=partition_solar_radiation, method="Olyphant", lat=40, sol.elev=60)
points(seq(0,1,0.1), r.seq, type = "l")
r.seq= lapply(seq(0,1,0.1), FUN=partition_solar_radiation, method="Reindl-1", lat=40, sol.elev=60)
points(seq(0,1,0.1), r.seq, type = "l")
r.seq= lapply(seq(0,1,0.1), FUN=partition_solar_radiation, method="Reindl-2", lat=40, sol.elev=60)
points(seq(0,1,0.1), r.seq, type = "l")
r.seq= lapply(seq(0,1,0.1), FUN=partition_solar_radiation, method="Lam_Li", lat=40, sol.elev=60)
points(seq(0,1,0.1), r.seq, type = "l")
#CHECKED
```

#Allometric functions
```{r}
plot(1:50, sa_from_mass(1:50,"lizard"), type="l", xlab = "m (g)", ylab = "surface area (m2)")
points(1:50, sa_from_mass(1:50,"frog"), type="l", col="blue")
points(1:50, sa_from_mass(1:50,"salamander"), type="l", col="green")
points(seq(0.1,5,0.2), sa_from_mass(seq(0.1,5,0.2),"insect"), type="l", col="purple")

#CHECKED
```

```{r}
plot(seq(0.05,0.25,0.01), mass_from_length(seq(0.05,0.25,0.01),"lizard"), type="l", xlab = "length (m)", ylab = "mass (g)", ylim=c(0,100))
points(seq(0.05,0.25,0.01), mass_from_length(seq(0.05,0.25,0.01),"salamander"), type="l", col="blue")
points(seq(0.05,0.25,0.01), mass_from_length(seq(0.05,0.25,0.01),"frog"), type="l", col="red")
points(seq(0.05,0.25,0.01), mass_from_length(seq(0.05,0.25,0.01),"snake"), type="l", col="green")
points(seq(0.05,0.25,0.01), mass_from_length(seq(0.05,0.25,0.01),"turtle"), type="l", col="orange")
points(seq(0.01,0.10,0.01), mass_from_length(seq(0.01,0.10,0.01),"insect"), type="l", col="purple")
#plot(log10(seq(0.05,0.25,0.01)*1000), log10(mass_from_length(seq(0.05,0.25,0.01),"lizard")), type="l")

#CHECKED
```

```{r}
plot(seq(0.001, 0.01, 0.001), sa_from_volume(seq(0.001, 0.01, 0.001),"lizard"), type="l", xlab = "volume (m^3)", ylab = "sa (m^2)")
points(seq(0.001, 0.01, 0.001), sa_from_volume(seq(0.001, 0.01, 0.001),"frog"), type="l", col="red")
points(seq(0.001, 0.01, 0.001), sa_from_volume(seq(0.001, 0.01, 0.001),"sphere"), type="l", col="green")
#CHECKED
```

```{r}
plot(seq(0.01, 0.05, 0.001), volume_from_length(seq(0.01, 0.05, 0.001),"lizard"), type="l", xlab = "length (m)", ylab = "volume (m^3)")
points(seq(0.01, 0.05, 0.001), volume_from_length(seq(0.01, 0.05, 0.001),"frog"), type="l")
points(seq(0.01, 0.05, 0.001), volume_from_length(seq(0.01, 0.05, 0.001),"sphere"), type="l")
#CHECKED
```

```{r}
plot(seq(0.01, 0.05, 0.001), sa_from_length(l=seq(0.01, 0.05, 0.001)), type="l", xlab = "length (m)", ylab = "surface area (m^2)")

#ROUGHLY CHECKED
```

```{r}
plot(seq(0, 90, 10), prop_silhouette_area(z=seq(0, 90, 10), taxa= "frog"), type="l", xlab = "zenith angle (degree)", ylab = "proportion silhouette area", ylim=range(0,0.5))
points(seq(0, 90, 10), prop_silhouette_area(z=seq(0, 90, 10), taxa= "lizard", raz=0, posture="prostrate"), type="l", col="lightblue")
points(seq(0, 90, 10), prop_silhouette_area(z=seq(0, 90, 10), taxa= "lizard", raz=0, posture="elevated"), type="l", col="blue")
points(seq(0, 90, 10), prop_silhouette_area(z=seq(0, 90, 10), taxa= "grasshopper"), type="l", col="green")
#CHECKED
```

```{r}
plot(seq(0, 90, 10), prop_silhouette_area_shapes(shape="spheroid", theta=seq(0, 90, 10), h=0.4, d=0.39), type="l", xlab = "theta (degree)", ylab = "proportion silhouette area", ylim=c(0,0.35), lty="dashed")
points(seq(0, 90, 10), prop_silhouette_area_shapes(shape="spheroid", theta=seq(0, 90, 10), h=0.4, d=0.3), type="l")
points(seq(0, 90, 10), prop_silhouette_area_shapes(shape="spheroid", theta=seq(0, 90, 10), h=0.4, d=0.2), type="l")
points(seq(0, 90, 10), prop_silhouette_area_shapes(shape="spheroid", theta=seq(0, 90, 10), h=0.4, d=0.1), type="l")
plot(seq(0, 90, 10), prop_silhouette_area_shapes(shape="cylinder flat ends", theta=seq(0, 90, 10), h=0.4, d=0.4), type="l", lty="dashed", xlab = "theta (degree)", ylab = "proportion silhouette area", ylim=c(0,0.35))
points(seq(0, 90, 10), prop_silhouette_area_shapes(shape="cylinder flat ends", theta=seq(0, 90, 10), h=0.4, d=0.2), type="l")
points(seq(0, 90, 10), prop_silhouette_area_shapes(shape="cylinder flat ends", theta=seq(0, 90, 10), h=0.4, d=0.1), type="l")
points(seq(0, 90, 10), prop_silhouette_area_shapes(shape="cylinder flat ends", theta=seq(0, 90, 10), h=0.4, d=0.05), type="l")
plot(seq(0, 90, 10), prop_silhouette_area_shapes(shape="cylinder hemisphere ends", theta=seq(0, 90, 10), h=0.4, d=0.4), type="l", lty="dotted", xlab = "theta (degree)", ylab = "proportion silhouette area", ylim=c(0,0.35))
points(seq(0, 90, 10), prop_silhouette_area_shapes(shape="cylinder hemisphere ends", theta=seq(0, 90, 10), h=0.4, d=0.2), type="l")
points(seq(0, 90, 10), prop_silhouette_area_shapes(shape="cylinder hemisphere ends", theta=seq(0, 90, 10), h=0.4, d=0.1), type="l")
points(seq(0, 90, 10), prop_silhouette_area_shapes(shape="cylinder hemisphere ends", theta=seq(0, 90, 10), h=0.4, d=0.05), type="l")
#CHECKED AGAINST CAMPBELL AND NORMAN Fig 11.6
```

#Energy balance functions
```{r}
plot(293:313, Qconduction_animal(T_g= 293:313,T_b=303,d=10^-6,K=0.5,A=10^-3, proportion=0.2), type="l", xlab = "ground temperature (C)", ylab = "conductance (W)")
#CHECKED
```

```{r}
plot(293:313, Qconduction_substrate(T_g= 293:313,T_b=303,D=0.01,K_g=0.3,A=10^-2, proportion=0.2), type="l", xlab = "ground temperature (C)", ylab = "conductance (W)")
#CHECKED
```

```{r}
plot(293:313, Qconvection(T_a= 303,T_b= 293:313,H=10.45,A=0.0025, proportion=0.85), type="l", xlab = "ground temperature (C)", ylab = "convection (W)")
#CHECKED
```

```{r}
plot(seq(0,3,0.25), heat_transfer_coefficient(V=seq(0,3,0.25),D=0.05,K= 25.7 * 10^(-3),nu= 15.3 * 10^(-6), "sphere"), type="l", xlab = "Air velocity (m/s)", ylab = "heat transfer coefficient, H_L (W m^-2 K^-1)")
points(seq(0,3,0.25), heat_transfer_coefficient(V=seq(0,3,0.25),D=0.05,K= 25.7 * 10^(-3),nu= 15.3 * 10^(-6), "cylinder"), type="l")
points(seq(0,3,0.25), heat_transfer_coefficient(V=seq(0,3,0.25),D=0.05,K= 25.7 * 10^(-3),nu= 15.3 * 10^(-6), "frog"), type="l")
points(seq(0,3,0.25), heat_transfer_coefficient(V=seq(0,3,0.25),D=0.05,K= 25.7 * 10^(-3),nu= 15.3 * 10^(-6), "lizard_surface"), type="l")
points(seq(0,3,0.25), heat_transfer_coefficient(V=seq(0,3,0.25),D=0.05,K= 25.7 * 10^(-3),nu= 15.3 * 10^(-6), "lizard_elevated"), type="l")
points(seq(0,3,0.25), heat_transfer_coefficient(V=seq(0,3,0.25),D=0.05,K= 25.7 * 10^(-3),nu= 15.3 * 10^(-6), "flyinginsect"), type="l")
points(seq(0,3,0.25), heat_transfer_coefficient(V=seq(0,3,0.25),D=0.05,K= 25.7 * 10^(-3),nu= 15.3 * 10^(-6), "spider"), type="l")
#CHECKED
```

```{r}
plot(seq(0,3,0.25), heat_transfer_coefficient_approximation(V=seq(0,3,0.25),D=0.05,K= 25.7 * 10^(-3),nu= 15.3 * 10^(-6), "sphere"), type="l", xlab = "Air velocity (m/s)", ylab = "heat transfer coefficient, H_L (W m^-2 K^-1)")
points(seq(0,3,0.25), heat_transfer_coefficient_approximation(V=seq(0,3,0.25),D=0.05,K= 25.7 * 10^(-3),nu= 15.3 * 10^(-6), "frog"), type="l")
points(seq(0,3,0.25), heat_transfer_coefficient_approximation(V=seq(0,3,0.25),D=0.05,K= 25.7 * 10^(-3),nu= 15.3 * 10^(-6), "lizard"), type="l")
points(seq(0,3,0.25), heat_transfer_coefficient_approximation(V=seq(0,3,0.25),D=0.05,K= 25.7 * 10^(-3),nu= 15.3 * 10^(-6), "flyinginsect"), type="l")
points(seq(0,3,0.25), heat_transfer_coefficient_approximation(V=seq(0,3,0.25),D=0.05,K= 25.7 * 10^(-3),nu= 15.3 * 10^(-6), "spider"), type="l")
#CHECKED
```

```{r}
plot(seq(0,3,0.25), heat_transfer_coefficient_simple(V=seq(0,3,0.25),D=0.05), type="l", xlab = "Air velocity (m/s)", ylab = "heat transfer coefficient, H_L (W m^-2 K^-1)")
#CHECKED
```

```{r}
plot(seq(100,1000,100), Qradiation_absorbed(a=0.9, A=1, psa_dir=0.4, psa_ref=0.4, S_dir=seq(100,1000,100), S_dif=200, a_s=0.5), type="l", xlab = "direct solar radiation (W/m^2)", ylab = "solar radiation absorbed (W)", lty="dashed")
points(seq(100,1000,100), Qradiation_absorbed(a=0.9, A=1, psa_dir=0.2, psa_ref=0.4, S_dir=seq(100,1000,100), S_dif=200, a_s=0.5), type="l")
points(seq(100,1000,100), Qradiation_absorbed(a=0.45, A=1, psa_dir=0.4, psa_ref=0.4, S_dir=seq(100,1000,100), S_dif=200, a_s=0.5), type="l")
points(seq(100,1000,100), Qradiation_absorbed(a=0.9, A=1, psa_dir=0.4, psa_ref=0.4, S_dir=seq(100,1000,100), S_dif=200, a_s=0.2), type="l")
#CHECKED
```

```{r}
plot(293:313, Qemitted_thermal_radiation(epsilon=0.96, A=1, psa_dir=0.4, psa_ref=0.6, T_b=293:313, T_g=293, T_a=298, enclosed=FALSE), type="l", xlab = "body surface temperature (K)", ylab = "emitted thermal radiation, Qemit (W)", lty="dashed")
points(293:313, Qemitted_thermal_radiation(epsilon=0.96, A=0.5, psa_dir=0.4, psa_ref=0.6, T_b=293:313, T_g=293, T_a=298, enclosed=FALSE), type="l")
points(293:313, Qemitted_thermal_radiation(epsilon=0.96, A=1, psa_dir=0.2, psa_ref=0.8, T_b=293:313, T_g=293, T_a=298, enclosed=FALSE), type="l")
points(293:313, Qemitted_thermal_radiation(epsilon=0.96, A=1, psa_dir=0.4, psa_ref=0.6, T_b=293:313, T_g=283, T_a=298, enclosed=FALSE), type="l")
points(293:313, Qemitted_thermal_radiation(epsilon=0.96, A=1, psa_dir=0.4, psa_ref=0.6, T_b=293:313, T_g=283, T_a=298, enclosed=TRUE), type="l", lty="dotted")
#CHECKED
```

```{r}
vp= saturation_vapor_pressure(293:313)#kPa
#convert to kg/m^3
rho_s= vp*0.032 #kg/m^3

vp= saturation_vapor_pressure(293:313-10)#kPa
#convert to kg/m^3
rho_a= vp*0.032 #kg/m^3

temps= 293:313
Qevaps= rep(NA,21)
Qevaps_wet= rep(NA,21)

for(ind in 1:21){
 Qevaps[ind]=Qevaporation(A=0.1, T_b=temps[ind], taxa="amphibian", rho_s=rho_s[ind], rho_a=rho_a[ind], h=0.5, H=20, r_i=50) 
Qevaps_wet[ind]=Qevaporation(A=0.1, T_b=temps[ind], taxa="amphibian_wetskin", rho_s=rho_s[ind], rho_a=rho_a[ind], h=0.5, H=20, r_i=50) 
 }

plot(temps, Qevaps, type="l", xlab = "body temperature (K)", ylab = "evaporative heat loss (W)", lty="dashed", ylim=c(0,400))

points(temps, Qevaps_wet, type="l", lty="dotted")

Qevap= unlist(lapply(293:313, FUN=Qevaporation, A=0.1, taxa="lizard"))
points(293:313, Qevap, type="l")

#CHECKED
```

```{r}
plot(10:30, saturation_water_vapor_pressure(T_a=10:30), type="l", xlab = "temperature (C)", ylab = "Saturation water vapor pressure (Pa)")
#CHECKED
```

```{r}
plot(10:30, external_resistance_to_water_vapor_transfer(H=10:30), type="l", xlab = "heat transfer coefficient (W m^-2 C^-1)", ylab = "external resistance to water vapor transfer (s m^-1)")
#CHECKED
```


```{r}
plot(1:100, Qmetabolism_from_mass(m=1:100,"bird"), type="l", xlab = "mass(g)", ylab = "metabolism (W)", log='xy')
points(1:100, Qmetabolism_from_mass(m=1:100,"mammal"), type="l", lty="dashed")
points(1:100, Qmetabolism_from_mass(m=1:100,"reptile"), type="l", lty="dotted")
#Plot in Kj/day as in paper
plot(1:100, Qmetabolism_from_mass(m=1:100,"bird")*86.4, type="l", xlab = "mass(g)", ylab = "metabolism (kJ/day)", log='xy')
points(1:100, Qmetabolism_from_mass(m=1:100,"mammal")*86.4, type="l", lty="dashed")
points(1:100, Qmetabolism_from_mass(m=1:100,"reptile")*86.4, type="l", lty="dotted")
#CHECKED
```

```{r}
plot(1:100, Qmetabolism_from_mass_temp(m=1:100, T_b=303,"bird"), type="l", xlab = "mass (g)", ylab = "metabolism (W)", ylim=c(0,0.1))
points(1:100, Qmetabolism_from_mass_temp(m=1:100, T_b=303,"mammal"), type="l")
points(1:100, Qmetabolism_from_mass_temp(m=1:100, T_b=303,"reptile"), type="l")
points(1:100, Qmetabolism_from_mass_temp(m=1:100, T_b=303,"amphibian"), type="l")
points(1:100, Qmetabolism_from_mass_temp(m=1:100, T_b=303,"invertebrate"), type="l")
plot(293:313, Qmetabolism_from_mass_temp(m=5, T_b=293:313,"bird"), type="l", xlab = "temperature (K)", ylab = "metabolism (W)", ylim=c(0,0.1))
points(293:313, Qmetabolism_from_mass_temp(m=5, T_b=293:313,"mammal"), type="l")
points(293:313, Qmetabolism_from_mass_temp(m=5, T_b=293:313,"reptile"), type="l")
points(293:313, Qmetabolism_from_mass_temp(m=5, T_b=293:313,"amphibian"), type="l")
points(293:313, Qmetabolism_from_mass_temp(m=5, T_b=293:313,"invertebrate"), type="l")
#Plot as in Gillooly et al. Fig 1. 
B= Qmetabolism_from_mass_temp(m=5, T_b=263:333,"bird")
plot(1000/(263:333), log(B/5^0.75*60), type="l", xlab = "temperature (K)", ylab = "metabolism (W)")
#CHECKED
```

```{r}
plot(0:40, actual_vapor_pressure(Tdewpoint=0:40), type="l", xlab = "dewpoint temperature (C)", ylab = "vapor pressure (kPa)")
points(0:40, saturation_vapor_pressure(T_a=273:(40+273)), type="l", lty="dashed")
#CHECKED
```

```{r}
blr.seq= lapply(293:313, FUN=boundary_layer_resistance, e_s=2.4, e_a=2.5, elev=500, D=0.007, u=2)
plot(293:313, blr.seq, type = "l", xlab = "air temperature (K)", ylab = "boundary layer resistance (s cm^-1)")
blr.seq= lapply(sqrt(5:20), FUN=boundary_layer_resistance, T_a=293, e_s=2.4, e_a=2.5, elev=500, u=2)
plot(sqrt(5:20), blr.seq, type = "l", xlab = "diameter (m)", ylab = "boundary layer resistance (s cm^-1)")
#APPROXIMATELY CHECKED
```


```{r}
t.seq= lapply(20:40, FUN=Tb_salamander_humid, r_i=4,r_b=1,D=0.01,elev=500,e_a=2.5,e_s=2.3,Qabs=400, epsilon=0.96)
plot(20:40, t.seq, type = "l", xlab = "ambient temperature (C)", ylab = "humid operative temperature (C)")
abline(a=0, b=1, lty="dotted")
#CHECK WITH ERIC?
```

```{r}
plot(20:40, Qthermal_radiation_absorbed(T_a=20:40, T_g=30, epsilon_ground=0.97, a_longwave=0.965), type="l", xlab = "air temperature (C)", ylab = "thermal radiation absorbed (W)")

Qemitted_thermal_radiation(epsilon=0.96, A=1, psa_dir=0.4, psa_ref=0.6, T_b=303, T_g=293, T_a=298, enclosed=FALSE)

#CHECK WITH ERIC?
```

```{r}
plot(1:24, Tsoil(Tg_max=30, Tg_min=15, hour=1:24, depth=0), type="l", xlab = "hour", ylab = "soil temperature (C)", lty="dashed")
points(1:24, Tsoil(Tg_max=30, Tg_min=15, hour=1:24, depth=5), type="l")
points(1:24, Tsoil(Tg_max=30, Tg_min=15, hour=1:24, depth=10), type="l")
points(1:24, Tsoil(Tg_max=30, Tg_min=15, hour=1:24, depth=20), type="l", lty="dotted")

#CHECKED
```

```{r}
plot(1:30, Nusselt_number(H_L=1:30, D=0.01, K=0.5), type="l", xlab = "heat transfer coefficient (W m^-2 K^-1)", ylab = "Nusselt number")
#CHECKED
```

```{r}
plot(1:30, Prandtl_number(c_p=1:30, mu=0.00001, K=0.5), type="l", xlab = "specific heat at constant pressure (J mol^{-1} K^{-1})", ylab = "Prandtl number")
#CHECKED
```

```{r}
plot(seq(0,5,0.2), Reynolds_number(V=seq(0,5,0.2), D=0.001, nu=1.2), type="l", xlab = "wind speed (m/s)", ylab = "Reynolds number")
#CHECKED
```

```{r}
plot(seq(0,0.01,0.001), Grashof_number(Ta=30, Tg=35, D=seq(0,0.01,0.001), nu=1.2), type="l", xlab = "characteristic dimension (m)", ylab = "Grashof number")
points(seq(0,0.01,0.001), Grashof_number_Gates(Ta=30, Tg=35, beta=0.00367, D=seq(0,0.01,0.001), nu=1.2), type="l", col="red")
#CHECKED, WHY DIFFERENT BETWEEN BOOKS?
```

```{r}
plot(1:10, Nu_from_Re(Re=1:10, taxa="sphere"), type="l", xlab = "Re", ylab = "Nu", ylim=c(0,4))
points(1:10, Nu_from_Re(Re=1:10, taxa="cylinder"), type="l")
points(1:10, Nu_from_Re(Re=1:10, taxa="frog"), type="l")
points(1:10, Nu_from_Re(Re=1:10, taxa="lizard_traverse_to_air_flow"), type="l")
points(1:10, Nu_from_Re(Re=1:10, taxa="lizard_parallel_to_air_flow"), type="l")
points(1:10, Nu_from_Re(Re=1:10, taxa="lizard_surface"), type="l")
points(1:10, Nu_from_Re(Re=1:10, taxa="lizard_elevated"), type="l")
points(1:10, Nu_from_Re(Re=1:10, taxa="flyinginsect"), type="l")
points(1:10, Nu_from_Re(Re=1:10, taxa="spider"), type="l")
#CHECKED
```

```{r}
Nu_from_Gr(Gr=5)
#CHECKED
```

```{r}
Free_or_forced_convection(Gr=100, Re=5)
#CHECKED
```

#OperativeTemperatureFunctions
```{r}
plot(293:313, Tb_CampbellNorman(T_a=293:313, S=823, epsilon=0.96, c_p=29.3, D=0.17, V=1), type="l", xlab = "air temperature (C)", ylab = "body temperature (C)")
abline(a=0, b=1, lty="dotted")
plot(seq(0,800,200), Tb_CampbellNorman(T_a=293, S=seq(0,800,200), epsilon=0.96, c_p=29.3, D=0.17, V=1), type="l", xlab = "solar and thermal radiation absorbed (W m^-2)", ylab = "body temperature (C)")
abline(a=293, b=0, lty="dotted")
#CHECKED AGAINST EXAMPLE IN BOOK FOR PERSON
```

```{r}
Qnet_Gates(Qabs=500, Qemit=10, Qconv=100, Qcond=100, Qmet=10, Qevap=5)

#CHECKED
```

```{r}
t.seq= lapply(293:313, FUN=Tb_Gates, A=0.1, D=0.001, psa_dir=0.6, psa_ref=0.4, psa_air=0.6, psa_g=0.0, T_g=303, Qabs=10, epsilon=0.95, H_L=10, ef=1.3, K=0.5)
plot(293:313, t.seq, type = "l", xlab = "ambient temperature (C)", ylab = "body temperature (C)", xlim=c(295,315), ylim=c(295,315))
abline(a=0,b=1, lty="dotted")
#vary radiation
t.seq= lapply(seq(0,100,10), FUN=Tb_Gates, A=0.1, D=0.001, psa_dir=0.6, psa_ref=0.4, psa_air=0.6, psa_g=0.2, T_a=303, T_g=303, epsilon=0.95, H_L=10, ef=1.3, K=0.5)
plot(seq(0,100,10), t.seq, type = "l", xlab = "radiation absorbed (W)", ylab = "body temperature (C)")
abline(a=303,b=0, lty="dotted")

#CHECKED
```

#biophysmodel_Colias
```{r}
t.seq= lapply(20:40, FUN=Tb_butterfly, Tg=25, Tg_sh=20, u=0.4, H_sdir=300, H_sdif=100, z=30, D=0.36, delta=1.46, alpha=0.6, r_g=0.3)
plot(20:40, t.seq, type = "l", xlab = "ambient temperature (C)", ylab = "body temperature (C)")
abline(a=0,b=1, lty="dotted")
t.seq= lapply(seq(0,800,20), FUN=Tb_butterfly, T_a=25, Tg=25, Tg_sh=25, u=0.4, H_sdif=100, z=30, D=0.36, delta=1.46, alpha=0.6, r_g=0.3)
plot(seq(0,800,20), t.seq, type = "l", xlab = "Direct radiation (W)", ylab = "body temperature (C)")
abline(a=25,b=0, lty="dotted")

#CHECKED
```

#biophysmodel_Grasshopper
```{r}
t.seq= lapply(20:40, FUN=Tb_grasshopper, T_g=25, u=0.4, H=800, K_t=0.7, psi=30, L=0.05, Acondfact=0.00, z=0.001, abs=0.7, r_g=0.3)
plot(20:40, t.seq, type = "l", xlab = "ambient temperature (C)", ylab = "body temperature (C)", xlim=c(20,40), ylim=c(20,40))
abline(a=0,b=1, lty="dotted")
t.seq= lapply(seq(0,800,20), FUN=Tb_grasshopper, T_a=25, T_g=25, u=0.4, K_t=0.7, psi=30, L=0.05, Acondfact=0.0, z=0.001, abs=0.7, r_g=0.3)
plot(seq(0,800,20), t.seq, type = "l", xlab = "Direct radiation (W)", ylab = "body temperature (C)")
abline(a=25,b=0, lty="dotted")

#CHECKED, clean up code?
```

#biophysmodel_Sceloporus
```{r}
#sun, surface
t.seq= lapply(20:40, FUN=Tb_lizard, T_g=30, u=0.1, svl=60, m=10, psi=34, rho_S=0.7, elev=500, doy=200, sun=TRUE, surface=TRUE, alpha_S=0.9, alpha_L=0.965, epsilon_s=0.965, F_d=0.8, F_r=0.5, F_a=0.5, F_g=0.5)
plot(20:40, t.seq, type = "l", xlab = "ambient temperature (C)", ylab = "body temperature (C)", xlim=c(20,51), ylim=c(20,51))
abline(a=0,b=1, lty="dotted")
#shade, surface
t.seq= lapply(20:40, FUN=Tb_lizard, T_g=30, u=0.1, svl=60, m=10, psi=34, rho_S=0.7, elev=500, doy=200, sun=FALSE, surface=TRUE, alpha_S=0.9, alpha_L=0.965, epsilon_s=0.965, F_d=0.8, F_r=0.5, F_a=0.5, F_g=0.5)
points(20:40, t.seq, type = "l", col="green")
#sun, above surface
t.seq= lapply(20:40, FUN=Tb_lizard, T_g=30, u=0.1, svl=60, m=10, psi=34, rho_S=0.7, elev=500, doy=200, sun=TRUE, surface=FALSE, alpha_S=0.9, alpha_L=0.965, epsilon_s=0.965, F_d=0.8, F_r=0.5, F_a=0.5, F_g=0.5)
points(20:40, t.seq, type = "l", col="purple")
#shade, above surface
t.seq= lapply(20:40, FUN=Tb_lizard, T_g=30, u=0.1, svl=60, m=10, psi=34, rho_S=0.7, elev=500, doy=200, sun=FALSE, surface=FALSE, alpha_S=0.9, alpha_L=0.965, epsilon_s=0.965, F_d=0.8, F_r=0.5, F_a=0.5, F_g=0.5)
points(20:40, t.seq, type = "l", col="blue")

#vary zenith angle
t.seq= lapply(0:90, FUN=Tb_lizard, T_a=30, T_g=30, u=0.1, svl=60, m=10, rho_S=0.7, elev=500, doy=200, sun=TRUE, surface=TRUE, alpha_S=0.9, alpha_L=0.965, epsilon_s=0.965, F_d=0.8, F_r=0.5, F_a=0.5, F_g=0.5)
plot(0:90, t.seq, type = "l", xlab = "zenith angle (degree)", ylab = "body temperature (C)")
abline(a=30,b=0, lty="dotted")

#CHECKED
#Include transient heat model in package?: https://github.com/JRubalcaba/BodyTemp.
```

#calculate_To
```{r}
t.seq= lapply(293:313, FUN=Tb_Fei, T_g=300, H=800, lw=30, shade=0.5, m=10.5, Acondfact=0.05, Agradfact=0.4)
plot(293:313, t.seq, type = "l", xlab = "ambient temperature (C)", ylab = "body temperature (C)")
abline(a=0,b=1, lty="dotted")

#STARTED TO FIX
```

#TsoilFunctions
```{r}
soil_conductivity(x=c(0.10,0.40,0.11,0.01,0.2, 0.18), lambda=c(0.10,0.40,0.11,0.01,0.2, 0.18), g_a=0.125)
```

```{r}
plot(seq(500,1700,100), soil_specific_heat(x_o=0.01, x_m=0.6, x_w=0.2, rho_so=seq(500,1700,100)), type="l", xlab = "bulk density (kg/m3)", ylab = "soil specific heat (J kg^-1 K-1)")
```

```{r}
soil_temperature_integrand(x=c(0.10,0.40,0.11,0.01,0.2, 0.18), L=-10,z0=0.2)
```

```{r}
soil_temperature_equation(L=-10, rho_a=1.177, c_a=1006, k=.41, V_inst=0.3, z_r=1.5, z0=0.02, T_inst=265, T_s=20)
```

```{r}
library(deSolve)

temp_vector= diurnal_temp_variation_sine(T_max=20, T_min=-10, t=rep(1:24,4))
wind_speed_vector= runif(96, min=0, max=0.4)
time_vector= rep(1:24,4)
solrad_vector= unlist(lapply(1:24, FUN=diurnal_radiation_variation, doy=172, solrad=8000, lon=-112.07, lat=33.45))
solrad_vector= rep(solrad_vector,4)

params=list(SSA=0.7, epsilon_so=0.98, k_so=0.293, c_so=800, dz=0.05, z_r=1.5, z0=0.02, H=solrad_vector, T_a=temp_vector, u=wind_speed_vector, rho_a=1.177,rho_so=1620, c_a=1006, TimeIn=time_vector, dt=60*60, shade=FALSE)

soil_temperature_function(j=1,T_so= rep(20,13), params=params)

Tsoil= soil_temperature(z_r.intervals=12,z_r=1.5, z=2, T_a=temp_vector, u=wind_speed_vector, Tsoil0= 20, z0=0.02, SSA=0.7, TimeIn=time_vector, H= solrad_vector, water_content=0.2, air_pressure=85, rho_so=1620, shade=FALSE)

plot(1:96, temp_vector, type = "l", xlab = "hour", ylim=c(-10,50))
points(1:96, wind_speed_vector, lty="dotted", type="l")
points(1:96, Tsoil, lty="dashed", type="l", col="red")

```

#DRYWETAIR
```{r}
DRYAIR(db=30, bp=100*1000, alt=0)
```

```{r}
VAPPRS(db=30)
```

```{r}
WETAIR(db=30, wb=28, rh=60, bp=100*1000)
```

#TPC FUNCTIONS
```{r}
plot(0:60, TPC(T=0:60, Topt=30, CTmin=10, CTmax=40), type="l", ylim=c(0,3), ylab="performance", xlab="temperature (C)")
points(0:60, TPC.beta(T=0:60, shift=-1, breadth=0.1, aran=0, tolerance= 43, skew=0.7), type="l", lty="dashed")
```