---
title: "List of symbols"
author: "TrEnCh project, Buckley Lab, Department of Biology, University of Washington"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{List of symbols}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The tables below compile the symbols which are used by TrenchR functions:

### Parameters

+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| Symbol              | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                |                 |
+=====================+============================================================================================================================================================================================================================================================================================================================================================================================================================================================+================:+
| $A$                 | surface or cross-sectional area ($m^2$)                                                                                                                                                                                                                                                                                                                                                                                                                    |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $a$                 | altitude angle of the sun (degrees) (subscripts: s, for normal to a slope; c ,for the axis of a cylinder); solar absorptivity (proportion) (subscripts: $l$, lizard thermal absorptivity; $s$, lizard solar absorptivity)                                                                                                                                                                                                                                                                                                                 |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $Acondfact$         | proportion of the animal surface area that is in contact with the ground                                                                                                                                                                                                                                                                                                                                                                                   |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $Agradfact$         | proportion of the animal projected area exposed to radiation from the ground                                                                                                                                                                                                                                                                                                                                                                               |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $air_{pressure}$    | air pressure (kPa)                                                                                                                                                                                                                                                                                                                                                                                                                                         |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $aran$              | scale performance value for performance curve? if aran = 0, no scaling; if aran = 1, includes a thermodynamic effect on mean performance                                                                                                                                                                                                                                                                                                                   |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $breadth$           | breadth of the thermal performance curve                                                                                                                                                                                                                                                                                                                                                                                                                   |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $c$                 | specific heat capacity (subscripts: $a$, air; $p$, air at constant pressure; $so$, soil) ($J kg^{-1}K^{-1}$ or $J kg^{-1}{°C}^{-1}$)                                                                                                                                                                                                                                                                                                                       |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $CT$                | critical thermal limit ($°C$) (subscripts: min, minima; max, maxima), the lower and upper temperature limit for performance                                                                                                                                                                                                                                                                                                                                |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $D$                 | characteristic dimension ($m$); thoracic diameter ($cm$)                                                                                                                                                                                                                                                                                                                                                                                                   |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $d$                 | thickness of material ($m$); diameter of a cylinder ($m$)                                                                                                                                                                                                                                                                                                                                                                                                  |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $day$ or $doy$      | day of year                                                                                                                                                                                                                                                                                                                                                                                                                                                |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $deg$               | angle (degrees)                                                                                                                                                                                                                                                                                                                                                                                                                                            |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $depth$             | depth ($cm$)                                                                                                                                                                                                                                                                                                                                                                                                                                               |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $e$                 | water vapor pressure ($N m^{-2}, mbar$) (subscripts: $a$, of the air; $s$, at saturation)                                                                                                                                                                                                                                                                                                                                                                  |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $ef$                | enhancement factor, used to adjust convective heat transfer coefficient to field conditions                                                                                                                                                                                                                                                                                                                                                                |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $elev$              | elevation above mean sea level ($m$).                                                                                                                                                                                                                                                                                                                                                                                                                      |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $F$                 | view factor between the animal and radiation stream (dimensionless) (subscripts: $a$, atmospheric radiation; $d$, diffuse solar radiation; $g$, ground thermal radiation; $r$, reflected solar radiation)                                                                                                                                                                                                                                                  |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $g_{a}$             | a shape factor for soil particles                                                                                                                                                                                                                                                                                                                                                                                                                              |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $H_L$ or $H$        | convective heat transfer coefficient ($W m^{-2}{°C}^{-1}$ or $W m^{-2}K^{-1}$)                                                                                                                                                                                                                                                                                                                                                                 |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $h$                 | height ($m$); length of a cylinder ($m$); relative humidity (decimal fraction); Planck's constant ($J s$); hour angle (rad)                                                                                                                                                                                                                                                                                                                                     |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $hp$                | mean month relative humidity (percentage)                                                                                                                                                                                                                                                                                                                                                                                                                         |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $hour$              | hour (0-24)                                                                                                                                                                                                                                                                                                                                                                                                                                                |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $K$                 | thermal conductance ($W m^{-2}{°C}^{-1}$) (subscripts f, fur; g, substrate; s, skin; sf, skin and fur; o, overall heat conductance for an animal; c, surface boundary layer for convection; so, soil).                                                                                                                                                                                                                                                     |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $k$                 | von Karman's constant (dimensionless), k\~0.41                                                                                                                                                                                                                                                                                                                                                                                                             |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $k_{so}$            | soil thermal conductivity ($W m^{-1}K^{-1}$ or $W m^{-1}C^{-1}$)                                                                                                                                                                                                                                                                                                                                                                                                               |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $K_t$ or $kt$       | clearness index, the ratio of the global solar radiation measured at the surface to the total solar radiation at the top of the atmosphere (dimensionless)                                                                                                                                                                                                                                                                                                 |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $L$                 | Monin-Obukhov length ($m$), a measure of the instability of heat flow                                                                                                                                                                                                                                                                                                                                                                                      |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $l$ or $L$          | length ($m$)                                                                                                                                                                                                                                                                                                                                                                                                                                               |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $lon$               | longitude (degrees)                                                                                                                                                                                                                                                                                                                                                                                                                                        |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $lat$               | latitude (degrees)                                                                                                                                                                                                                                                                                                                                                                                                                                         |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $LDT$               | lower developmental threshold ($°C$)                                                                                                                                                                                                                                                                                                                                                                                                                       |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $lw$                | downward flux of near-infrared radiation ($Wm^{-2}$)                                                                                                                                                                                                                                                                                                                                                                                                       |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $m$                 | mass ($kg$ or $g$); air mass (dimensionless)                                                                                                                                                                                                                                                                                                                                                                                                               |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $P$                 | monthly precipitation ($mm$)                                                                                                                                                                                                                                                                                                                                                                                                                               |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $psa$               | proportion surface exposed (dimensionless) (subscripts: $air$, for exposure to air; $ref$, for exposure to ground; $dir$, for exposure to sky or enclosure; $g$, for exposure to substrate)                                                                                                                                                                                                                                                                |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $Q_{abs}$           | solar and thermal radiation absorbed ($W$)                                                                                                                                                                                                                                                                                                                                                                                                                 |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $Q_{emit}$          | thermal radiation emitted ($W$)                                                                                                                                                                                                                                                                                                                                                                                                                            |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $Q_{conv}$          | energy exchange between an animal and the surrounding substance due to convection ($W$)                                                                                                                                                                                                                                                                                                                                                                    |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $Q_{cond}$          | energy exchange between an animal and the surface due to conduction ($W$)                                                                                                                                                                                                                                                                                                                                                                                  |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $Q_{met}$           | energy emitted due to metabolism ($W$)                                                                                                                                                                                                                                                                                                                                                                                                                     |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $Q_{evap}$          | energy emitted due to evaporative water loss ($W$)                                                                                                                                                                                                                                                                                                                                                                                                         |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $r$                 | reflectance (decimal fraction) (subscripts: $g$, of ground; $S$, to direct sunlight; $s$, to skylight); diffusion resistance to water vapor ($s m^{-1}$) (subscripts: $b$, boundary layer; $i$, internal or intercellular); resistance to heat flow ($s m^{-1}$) (subscripts: $h$, $ha$, boundary layer; $j$, diffusion resistance to molecular species j; radius ($m$) (subscripts: $b$, of inside body wall of animal; $r$, of outer surface of animal)  |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $rad$               | angle (radians)                                                                                                                                                                                                                                                                                                                                                                                                                                            |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $raz$               | solar azimuth angle (degrees)                                                                                                                                                                                                                                                                                                                                                                                                                              |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $S$                 | amount of sunlight incident upon the earth's surface ($W m^{-2}$) (subscripts: $dir$, direct solar radiation; $dif$, diffuse solar radiation; $h$, on a horizontal surface; $ref$, reflected solar radiation)                                                                                                                                                                                                                                              |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $shade$             | whether soil temperature is calculated in the shade or not                                                                                                                                                                                                                                                                                                                                                                                                 |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $shift$             | mode of the thermal performance curve                                                                                                                                                                                                                                                                                                                                                                                                                      |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $skew$              | skewness of the thermal performance curve                                                                                                                                                                                                                                                                                                                                                                                                                  |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $sol.elev$          | solar elevation angles (degrees)                                                                                                                                                                                                                                                                                                                                                                                                                           |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $SSA$               | solar absorptivity of soil surface (proportion)                                                                                                                                                                                                                                                                                                                                                                                                            |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $svl$               | lizard snout vent length ($mm$)                                                                                                                                                                                                                                                                                                                                                                                                                            |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $t$                 | time ($hr$ or $s$) (subscripts: $as$, after sunset; $n$, time of minimum temperature; $r$, sunrise; $s$, sunset; $p$, rise the following day; $x$, time of maximum temperature)                                                                                                                                                                                                                                                                            |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $T$                 | temperature ($°C$ or $K$ or $°F$) (subscripts: $a$, air; $g$, ground; $s$, surface; $sh$, shade; $sky$, effective radiant temperature of the sky)                                                                                                                                                                                                                                                                                                          |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $T_{dewpoint}$      | dewpoint temperature ($°C$)                                                                                                                                                                                                                                                                                                                                                                                                                                |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $T_{e}$             | Operative environmental temperature ($°C$)                                                                                                                                                                                                                                                                                                                                                                                                                 |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $T_{max}$           | maximum temperature of the day ($°C$)                                                                                                                                                                                                                                                                                                                                                                                                                      |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $T_{min}$           | minimum temperature of the day ($°C$)                                                                                                                                                                                                                                                                                                                                                                                                                      |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $Tg_{max}$          | maximum soil surface temperature of the day ($°C$)                                                                                                                                                                                                                                                                                                                                                                                                         |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $Tg_{min}$          | minimum soil surface temperature of the day ($°C$)                                                                                                                                                                                                                                                                                                                                                                                                         |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $T_{opt}$           | thermal optima, the temperature at which peak performance occurs ($°C$)                                                                                                                                                                                                                                                                                                                                                                                    |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $T_{soil0}$         | initial soil temperature ($°C$)                                                                                                                                                                                                                                                                                                                                                                                                                            |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $tolerance$         | maximal breath ($°C$) of the thermal performance curve                                                                                                                                                                                                                                                                                                                                                                                                     |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $u$                 | wind speed ($m s^{-1}$) (subscripts: $r$, reference height or heights)                                                                                                                                                                                                                                                                                                                                                                                     |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $UDT$               | upper developmental threshold ($°C$)                                                                                                                                                                                                                                                                                                                                                                                                                       |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $V$                 | volume ($m^{3}$)                                                                                                                                                                                                                                                                                                                                                                                                                    |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $water_{content}$   | water content (percent)                                                                                                                                                                                                                                                                                                                                                                                                                                    |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $x$                 | vector of volume fractions of soil constituents (e.g., clay, quartz, minerals other than quartz, organic matter, water, air)                                                                                                                                                                                                                                                                                                                               |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $z$                 | distance, or height above a surface ($m$)                                                                                                                                                                                                                                                                                                                                                                                                |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $zr$                | reference height ($m$)                                                                                                                                                                                                                                                                                                                                                                                                                                     |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| $z0$                | roughness height ($m$)                                                                                                                                                                                                                                                                                                                                                                                                                                     |                 |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+

### Greek Symbols

+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
| Symbol     | Description                                                                                                                                                                                                                                                                    |                |
+============+================================================================================================================================================================================================================================================================================+===============:+
| $\alpha$   | angle (rad or degrees); azimuth angle of the sun (degrees); time difference between time of maximum temperature and noon ($hr$)                                |                |
+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
| $\beta$    | slope angle, direction of normal from horizontal (degrees); time difference between time of maximum temperature and sunrise ($hr$)                                                                                                                                             |                |
+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
| $\delta$   | thoracic fur thickness ($mm$)                                                                                                                                                                                                                                                  |                |
+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
| $\epsilon$ | emissivity (decimal fraction) (subscripts: $a$, of atmosphere; $s$, surface emissivity); angle (radian or degree); angle between axis of a cylinder and direction of the sun's rays; equivalent temperature ($°C$); thermal absorptivity as a fraction (subscript: $so$, soil) |                |
+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
| $\gamma$   | decay parameter for rate of time change from sunset to time of minimum temperature                                                                                                                                                                                             |                |
+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
| $\lambda$  | vector of the thermal conductivities ($W m^{-1} K^{-1}$) of the soil constituents                                                                                                                                                                                              |                |
+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
| $\mu$      | dynamic viscosity ($mol\:s^{-1}m^{-1}$)                                                                                                                                                                                                                                        |                |
+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
| $\nu$      | kinematic viscosity coefficient ($m^2 s^{-1}$)                                                                                                                                                                                                                                 |                |
+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
| $\psi$     | solar zenith angle (degrees)                                                                                                                                                                                                                                                   |                |
+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
| $\rho$     | density ($kg m^{-3}$) (subscripts: $a$, of dry air; $j$, of molecular species; $o$, of standard air; $w$, of water vapor; $so$, of soil); radius of a cylinder ($m$); reflectivity (decimal fraction) (subscript: $S$, surface albedo)                                         |                |
+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
| $\tau$     | atmospheric transmissivity (proportion) (subscripts: $d$, to diffuse radiation; $t$, to total radiation); thermal time constant ($s$ or $hr$) (superscript: $a$, apparent)                                                                                                     |                |
+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
| $\theta$   | angle between the solar beam and the longitudinal axis (degrees)                                                                                                                                                                                                               |                |
+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+

### Dimensionless Groups

| Symbol |   Description   |     |
|--------|:---------------:|----:|
| $Gr$   | Grashof number  |     |
| $Nu$   | Nusselt number  |     |
| $Re$   | Reynolds number |     |
