# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples

on:
  push:
    branches: [main, master]]
  release:
    types: [published]

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      _R_CHECK_FORCE_SUGGESTS_: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      CRAN_REPO: https://packagemanager.rstudio.com/all/__linux__/focal/latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Query dependencies
        run: |
          install.packages('remotes', repos = c("CRAN" = Sys.getenv("CRAN_REPO")))
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install texlive-latex-base libharfbuzz-dev libfribidi-dev

      - name: Install package dependencies
        run: |
          remotes::install_deps(dependencies = TRUE, repos = c("CRAN" = Sys.getenv("CRAN_REPO")))
          install.packages(c("stringi", "stringr", "knitr"))
          remotes::install_github("tidyverse/tidytemplate")
          remotes::install_dev("pkgdown")
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Deploy package
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE, examples = FALSE)'
